[project]
name = "lux-ai-season-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jax>=0.4.38",
    "jaxlib>=0.4.38",
    "luxai-s3>=0.1.0",
    "numpy>=2.2.0",
    "ruff>=0.8.4",
]
